const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 3.0,
            numReviews: 10,
            description: 'high quantity product',
        },
        {
            _id: '2',
            name: 'CanonDSLR HD1.3',
            category: 'DSLR',
            image: '/images/p2.jpg',
            price: 640,
            countInStock: 13,
            brand: 'Canon',
            rating: 4.0,
            numReviews: 13,
            description: 'high quantity product',
        },
        {
            _id: '3',
            name: 'Nike Slim pants',
            category: 'pants',
            image: '/images/p3.jpg',
            price: 110,
            countInStock: 0,
            brand: 'Nike',
            rating: 4.8,
            numReviews: 14,
            description: 'high quantity product',
        },
        {
            _id: '4',
            name: 'Nike Slim Shirt',
            category: 'Books',
            image: '/images/p4.jpg',
            price: 150,
            countInStock: 0,
            brand: 'Nike',
            rating: 4.9,
            numReviews: 25,
            description: 'high quantity product',
        },
        {
            _id: '5',
            name: 'Cat',
            category: 'Pats',
            image: '/images/p5.jpg',
            price: 134,
            countInStock: 2,
            brand: 'Nike',
            rating: 4.1,
            numReviews: 20,
            description: 'high quantity product',
        },

    ],
};
export default data;